---
title: "rbvnorm"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{rbvnorm}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(rbvnormCAPPS)
library(ggplot2)
```

```{r}
rbvnorm <- function(iter, mu, sigma) {

  df <- data.frame(matrix(nrow = 0, ncol = 2)) # creating initial data frame
  x_2 <- rnorm(1, mean = mu[2], sd = sqrt(sigma[2, 2])) # generating seed value


  for (i in 1:iter) {

    x_1 <- rnorm(1, mean = mu[1] + sigma[1, 2] * (x_2 - mu[2])/sigma[2,2],
                 sd = sqrt(sigma[1, 1] - sigma[1, 2]^2 / sigma[2, 2]))

    x_2 <- rnorm(1, mean = mu[2] + sigma[2, 1] * (x_1 - mu[1])/sigma[1,1],
                 sd = sqrt(sigma[2, 2] - sigma[2, 1]^2 / sigma[1, 1]))

    df <- rbind(df, c(x_1, x_2))
  }
  colnames(df) <- c("X1", "X2")
  invisible(list(gibbs = df, iter = iter, mu = mu, sigma = sigma))
}
```

```{r}
gibbs <- rbvnorm(iter = 10000, mu = c(3, 6), sigma = matrix(c(8,-2,-2,4), nrow = 2, byrow = TRUE))
```


```{r}
tail(gibbs$gibbs)
gibbs$iter
gibbs$mu
gibbs$sigma
```


```{r, warning = FALSE}
df <- gibbs$gibbs

p <- ggplot(df, aes(x = X1, y = X2)) +
  geom_point()

#fit <- ellipse::ellipse(cor(x, y), centre = c(mean(x), mean(y)), scale = c(sd(x), sd(y)))

p + stat_ellipse(aes(fill = "ellipse"), level = 0.95, type = "norm", color = "red")
```

